- name: Install Docker and Deploy Application
  hosts: ec2
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Backend Image
      command: docker pull kesharagunathilaka/backend:latest

    - name: Pull Frontend Image
      command: docker pull kesharagunathilaka/frontend:latest

    - name: Run Backend Container
      command: docker run -d --name backend -p 5000:5000 kesharagunathilaka/backend:latest

    - name: Run Frontend Container
      command: docker run -d --name frontend -p 3000:3000 --env BACKEND_URL=http://{{ ansible_default_ipv4.address }}:5000 kesharagunathilaka/frontend:latest
